### ISSUE TITLE
在offlinenode4 上面执行会报错，怎么解决？

### ISSUE THREAD

**Issue by friendshingle** [bigdata-labs/spark2-hadoop2.6-hbase-labs#2]
vagrant@offlinenode4:/vagrant$ ansible-playbook ./ansible/playbook.yml -i ./ansible/inventory -u vagrant -k
SSH password: 
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will be removed in a future release. Deprecation warnings can be
 disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: 'include' for playbook includes. You should use 'import_playbook' instead. This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: Found variable using reserved name: hosts

PLAY [all] **********************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
fatal: [192.168.11.152]: FAILED! => {"msg": "Using a SSH password instead of a key is not possible because Host Key checking is enabled and sshpass does not support this.  Please add this host's fingerprint to your known_hosts file to manage this host."}
fatal: [192.168.11.153]: FAILED! => {"msg": "Using a SSH password instead of a key is not possible because Host Key checking is enabled and sshpass does not support this.  Please add this host's fingerprint to your known_hosts file to manage this host."}
fatal: [192.168.11.154]: FAILED! => {"msg": "Using a SSH password instead of a key is not possible because Host Key checking is enabled and sshpass does not support this.  Please add this host's fingerprint to your known_hosts file to manage this host."}
fatal: [192.168.11.151]: FAILED! => {"msg": "Using a SSH password instead of a key is not possible because Host Key checking is enabled and sshpass does not support this.  Please add this host's fingerprint to your known_hosts file to manage this host."}
        to retry, use: --limit @/vagrant/ansible/playbook.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
192.168.11.151             : ok=0    changed=0    unreachable=0    failed=1   
192.168.11.152             : ok=0    changed=0    unreachable=0    failed=1   
192.168.11.153             : ok=0    changed=0    unreachable=0    failed=1   
192.168.11.154             : ok=0    changed=0    unreachable=0    failed=1

**Comment by friendshingle** [comment]
从无到有开始搞，发现很多没有写的内容，如下：

Vagrant配合virtualbox有限制，试了好多个版本都不行，最后发现这个组合OK：
    vagrant_1.9.5.msi
    VirtualBox-5.1.30-118389-Win.exe
    
SSH登录 192.168.11.154，用户名 vagrant  密码 vagrant

在offlinenode4节点上面，安装以下包（但不能安装ansible，不兼容）：
    sudo apt-get update
    sudo apt install git build-essential libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext unzip python-pip sshpass
    sudo pip install paramiko PyYAML Jinja2 httplib2 six
    
安装ansible
    cd /opt
    sudo git clone git://github.com/ansible/ansible.git --recursive
    cd ./ansible
    source ./hacking/env-setup
    sudo pip install paramiko PyYAML Jinja2 httplib2 six

配置ansible
    sudo mkdir /etc/ansible
    sudo vi /etc/ansible/ansible.cfg

    /etc/ansible/ansible.cfg配置的内容为：
##########################################################################
[defaults]
# some basic default values...
hostfile       = /etc/ansible/hosts   \\指定默认hosts配置的位置
# library_path = /usr/share/my_modules/
remote_tmp     = $HOME/.ansible/tmp
pattern        = *
forks          = 5
poll_interval  = 15
sudo_user      = root  \\远程sudo用户
#ask_sudo_pass = True  \\每次执行ansible命令是否询问ssh密码
#ask_pass      = True  \\每次执行ansible命令时是否询问sudo密码
transport      = smart
remote_port    = 22
module_lang    = C
gathering = implicit
host_key_checking = False    \\关闭第一次使用ansible连接客户端是输入命令提示
log_path    = /var/log/ansible.log \\需要时可以自行添加。chown -R root:root ansible.log
system_warnings = False    \\关闭运行ansible时系统的提示信息，一般为提示升级
# set plugin path directories here, separate with colons
action_plugins     = /usr/share/ansible_plugins/action_plugins
callback_plugins   = /usr/share/ansible_plugins/callback_plugins
connection_plugins = /usr/share/ansible_plugins/connection_plugins
lookup_plugins     = /usr/share/ansible_plugins/lookup_plugins
vars_plugins       = /usr/share/ansible_plugins/vars_plugins
filter_plugins     = /usr/share/ansible_plugins/filter_plugins
fact_caching = memory
[accelerate]
accelerate_port = 5099
accelerate_timeout = 30
accelerate_connect_timeout = 5.0
# The daemon timeout is measured in minutes. This time is measured
# from the last activity to the accelerate daemon.
accelerate_daemon_timeout = 30
##########################################################################

这个不存在了，需要修改
    http://mirrors.tuna.tsinghua.edu.cn/apache/zookeeper/zookeeper-3.4.9/zookeeper-3.4.9.tar.gz
        ansible\roles\zookeeper\defaults\main.yml
           改为(改版本号)   version: 3.4.10

    http://apache.stu.edu.tw/hbase/1.2.4/hbase-1.2.4-bin.tar.gz
        ansible\roles\hbase\defaults\main.yml
            改为(改地址) hbase_download_url: "http://archive.apache.org/dist/hbase/{{hbase_version}}/{{hbase_tar_name}}"
    
    
    https://mirrors.tuna.tsinghua.edu.cn/apache/spark/spark-2.0.1/spark-2.0.1-bin-hadoop2.6.tgz
        不必改
        
拷贝下载的软件到 spark2-hadoop2.6-hbase-labs-master\ansible 目录，这个目录会自动mount到 /vagrant 中：
    hadoop-2.6.5.tar.gz
    hadoop-native-64-2.6.0.tar
    hbase-1.2.4.zip
    jdk-8u66-linux-x64.tar.gz
    spark-2.0.1-bin-hadoop2.6.tgz
    
打开目录 /vagrant
    cd /vagrant
    ansible-playbook ./ansible/playbook.yml -i ./ansible/inventory -u vagrant -k
        按提示输入密码 vagrant

**Comment by zacker330** [comment]
vagrant 与virtualbox之间的版本匹配问题，不属于这个repo的问题。
